In [10]:
import numpy as np
from scipy import optimize

In [39]:
def gradient_descent_fixed_step(f, x0, step_size=0.01, tol=1e-5, num_epochs=100):
    x = np.zeros([num_epochs, 4])
    x[0] = x0
    print(x[0])
    for k in range(num_epochs -1 ):
        x[k+1] = x[k] - step_size * f_grad(x[k])
        if np.linalg.norm(f_grad(x[k+1])) < tol:
            print("The number of iteration: {}".format(k + 1))
            break
            
        if (k+1) > 1000 and (k+1) % 1000 ==0:
            print(k+1, x[k+1])
    
    return x[k+1], x[0:k+2]

In [17]:
def gradient_descent_backtracking(f, x0, alpha=0.1, beta=0.1, tol=1e-5, num_epochs=100):
    x = np.zeros([num_epochs, 4])
    x[0] = x0
    t0 = 1
    for k in range(num_epochs -1 ):
        t = beta * t0
        x[k+1] = x[k] - alpha * t * f_grad(x[k])
        if np.linalg.norm(f_grad(x[k+1])) < tol:
            print("The number of iteration: {}".format(k + 1))
            break
            
        if (k+1) > 1000 and (k+1) % 1000 ==0:
            print(k+1, x[k+1])
    
    return x[k+1], x[0:k+2]

In [18]:
def gradient_descent_exact(f, x0, tol=1e-5, num_epochs=100):
    x = np.zeros([num_epochs, 4])
    x[0] = x0
    for k in range(num_epochs -1 ):
        g = lambda t: f((x[k] - t *  f_grad(x[k]))[0])
        t_r = optimize.minimize_scalar(g)
        x[k+1] = x[k] - t_r['x'] * f_grad(x[k])
        if np.linalg.norm(f_grad(x[k+1])) < tol:
            print("The number of iteration: {}".format(k + 1))
            break
            
        if (k+1) > 1000 and (k+1) % 1000 ==0:
            print(k+1, x[k+1])
    
    return x[k+1], x[0:k+2]

In [67]:
def gradient_descent_alpha(f, x0, tol=1e-5, num_epochs=100):
    x = np.zeros([num_epochs, 4])
    x[0] = x0
    alpha = 0.1
    for k in range(num_epochs - 1):
        g = lambda t: f((x[k] - t *  f_grad(x[k]))[0])
        t_r = optimize.minimize_scalar(g, bracket=(-10, -9))
        x[k+1] = x[k] - alpha * t_r['x'] * f_grad(x[k])
        if np.linalg.norm(f_grad(x[k+1])) < tol:
            print("The number of iteration: {}".format(k + 1))
            break
        
        if (k+1) > 1000 and (k+1) % 1000 ==0:
            print(k+1, x[k+1])
    return x[k+1], x[0:k+2]

### Min $f(\mathbf x)=(x_1+10x_2)^2+5(x_3-x_4)^2+(x_2-2x_3)^4+10(x_1-x_4)^4$

In [68]:
import sympy
sympy.init_printing()

x1, x2, x3, x4 = sympy.symbols("x1, x2, x3, x4")
f_sym = (x1 + 10 * x2)**2 + 5 * (x3 - x4)**2 + \
            (x2 - 2 * x3)**4 + 10 * (x1 - x4)**4
f_mat = sympy.Matrix([f_sym])
f_grad_sym = f_mat.jacobian([x1, x2, x3, x4])
f_lamb = sympy.lambdify((x1, x2, x3, x4), f_sym, 'numpy')
fgrad_lamb = sympy.lambdify((x1, x2, x3, x4), f_grad_sym, 'numpy')

In [69]:
def func_XY_to_X_Y(f):
    return lambda X: np.array(f(X[0], X[1], X[2], X[3]))

In [70]:
f = func_XY_to_X_Y(f_lamb)
f_grad = func_XY_to_X_Y(fgrad_lamb)

### Fixed Step Size

In [71]:
mini0_1, minis0_1 = gradient_descent_fixed_step(f, np.array([3, -1, 0, 1]), 
                                            step_size=1)
mini0_1

[ 3. -1.  0.  1.]


e:\a-soft\anaconda3\lib\site-packages\numpy\__init__.py:1: RuntimeWarning: overflow encountered in double_scalars
  """
e:\a-soft\anaconda3\lib\site-packages\numpy\__init__.py:1: RuntimeWarning: invalid value encountered in double_scalars
  """
e:\a-soft\anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in subtract
  


array([nan, nan, nan, nan])

In [72]:
mini0_2, minis0_2 = gradient_descent_fixed_step(f, np.array([3, -1, 0, 1]), 
                                            step_size=0.1)
mini0_2

[ 3. -1.  0.  1.]


e:\a-soft\anaconda3\lib\site-packages\numpy\__init__.py:1: RuntimeWarning: overflow encountered in double_scalars
  """
e:\a-soft\anaconda3\lib\site-packages\numpy\__init__.py:1: RuntimeWarning: invalid value encountered in double_scalars
  """
e:\a-soft\anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in subtract
  


array([nan, nan, nan, nan])

In [81]:
mini0_3, minis0_3 = gradient_descent_fixed_step(f, np.array([3, -1, 0, 1]), 
                                            step_size=0.001, num_epochs=10000)
mini0_3

[ 3. -1.  0.  1.]
2000 [ 0.26998282 -0.02659797  0.12734821  0.14119417]
3000 [ 0.20602868 -0.02041403  0.09933632  0.10575692]
4000 [ 0.17201153 -0.01708832  0.08374374  0.0875491 ]
5000 [ 0.15034454 -0.014958    0.07359031  0.07615667]
6000 [ 0.13507685 -0.01345173  0.06634232  0.06821519]
7000 [ 0.12360267 -0.01231712  0.06084869  0.0622898 ]
8000 [ 0.11458636 -0.0114241   0.05650589  0.05765763]
9000 [ 0.10726632 -0.0106982   0.05296441  0.05391142]


array([ 0.10117907, -0.01009398,  0.05000924,  0.05080545])

### Backtracking Line Search

In [89]:
mini1, minis1 = gradient_descent_backtracking(f, np.array([3, -1, 0, 1]), 
                                              alpha=0.01, beta=0.0002, num_epochs=10000)
mini1

2000 [ 2.54773556 -0.59141663  0.03408858  1.44113363]
3000 [ 2.47048908 -0.47738774  0.05875784  1.50103307]
4000 [ 2.41528131 -0.39915008  0.08460636  1.53495149]
5000 [ 2.37183058 -0.34519497  0.11066951  1.55469133]
6000 [ 2.33558624 -0.30768676  0.13641177  1.56579168]
7000 [ 2.30419765 -0.28130906  0.16149268  1.57125425]
8000 [ 2.27630705 -0.26246087  0.18567478  1.57286667]
9000 [ 2.25106005 -0.24870619  0.20878451  1.57176557]


array([ 2.22790422, -0.23840859,  0.23067349,  1.56871228])

### Exact Line Search

In [91]:
mini2, minis2 = gradient_descent_exact(f, np.array([3, -1, 0, 1]), 
                                       num_epochs=50000)
mini2

2000 [ 0.06733322 -0.00671844  0.03343267  0.03366926]
3000 [ 0.05444349 -0.00543646  0.02706702  0.02719237]
4000 [ 0.04690852 -0.00468579  0.02333543  0.0234157 ]
5000 [ 0.04182294 -0.00417871  0.02081317  0.02087009]
6000 [ 0.03809592 -0.00380688  0.01896302  0.01900606]
7000 [ 0.03521403 -0.00351926  0.01753152  0.01756552]
8000 [ 0.03289984 -0.00328823  0.01638149  0.01640922]
9000 [ 0.03098861 -0.0030974   0.01543138  0.01545457]
10000 [ 0.02937557 -0.00293631  0.0146293   0.01464905]
11000 [ 0.02799048 -0.00279797  0.01394042  0.0139575 ]
12000 [ 0.02678425 -0.00267748  0.01334038  0.01335536]
13000 [ 0.02572147 -0.00257131  0.01281163  0.01282489]
14000 [ 0.02477579 -0.00247683  0.01234108  0.01235293]
15000 [ 0.02392719 -0.00239204  0.01191878  0.01192946]
16000 [ 0.02316012 -0.0023154   0.01153702  0.01154671]
17000 [ 0.02246234 -0.00224568  0.01118972  0.01119856]
18000 [ 0.02182401 -0.00218189  0.01087199  0.01088009]
19000 [ 0.02123717 -0.00212325  0.01057986  0.01058733]


array([ 0.01306536, -0.00130658,  0.00651035,  0.00651209])

### $\alpha$

In [104]:
mini3_1, minis3_1 = gradient_descent_alpha(f, np.array([3, -1, 0, 1]),
                                           num_epochs=10000)
mini3_1

2000 [ 0.03040584 -0.00304259  0.01514214  0.01516334]
3000 [ 0.0205549  -0.00205533  0.01024022  0.01024699]
4000 [ 0.01568349 -0.00156819  0.00781437  0.00781756]
5000 [ 0.01278653 -0.00127875  0.00637146  0.00637308]
The number of iteration: 5337


array([ 0.01074116, -0.00107406,  0.00535247,  0.00535342])

different inital values:

In [123]:
mini3_2, minis3_2 = gradient_descent_alpha(f, np.array([3, -1, 0, 1]),
                                           tol=1e-8, num_epochs=int(1e+6))
mini3_2

2000 [ 0.03040584 -0.00304259  0.01514214  0.01516334]
3000 [ 0.0205549  -0.00205533  0.01024022  0.01024699]
4000 [ 0.01568349 -0.00156819  0.00781437  0.00781756]
5000 [ 0.01278653 -0.00127875  0.00637146  0.00637308]
6000 [ 0.00978992 -0.0009789   0.00487851  0.00487926]
7000 [ 0.00939559 -0.00093959  0.00468205  0.0046827 ]
8000 [ 0.00799795 -0.00079977  0.00398565  0.00398605]
9000 [ 0.00733631 -0.00073362  0.00365559  0.00365664]
10000 [ 0.00708471 -0.00070846  0.00353059  0.00353087]
11000 [ 0.00661805 -0.00066184  0.00329806  0.00329828]
12000 [ 0.00618431 -0.00061842  0.00308192  0.0030821 ]
13000 [ 0.00607121 -0.00060712  0.00302556  0.00302573]
14000 [ 0.00578278 -0.00057827  0.00288183  0.00288198]
15000 [ 0.00562271 -0.00056227  0.00280206  0.0028022 ]
16000 [ 0.00500582 -0.0005005   0.00249465  0.00249474]
17000 [ 0.0048678  -0.00048678  0.00242587  0.00242596]
18000 [ 0.00430752 -0.00043074  0.00214666  0.00214672]
19000 [ 0.00407416 -0.00040741  0.00203037  0.00203042]


array([ 0.00111715, -0.00011172,  0.00055674,  0.00055675])

In [124]:
mini3_3, minis3_3 = gradient_descent_alpha(f, np.array([10, -10, 10, 10]), 
                                           tol=1e-8, num_epochs=int(1e+6))
mini3_3

2000 [ 0.03473398 -0.00347183  0.01729303  0.01732567]
3000 [ 0.02532867 -0.00253694  0.01261644  0.01262908]
4000 [ 0.02082381 -0.00208334  0.01037415  0.01038119]
5000 [ 0.01783611 -0.00178315  0.00888649  0.00889091]
6000 [ 0.01432534 -0.00143255  0.00713799  0.00714028]
7000 [ 0.01249744 -0.00124978  0.00622744  0.00622896]
8000 [ 0.01124371 -0.00112433  0.00560284  0.00560395]
9000 [ 0.0097173  -0.00097175  0.00484235  0.00484306]
10000 [ 0.00896114 -0.00089607  0.00446558  0.00446614]
11000 [ 0.00775491 -0.00077547  0.00386455  0.00386491]
12000 [ 0.00700034 -0.00070002  0.00348856  0.00348882]
13000 [ 0.00675562 -0.00067554  0.00336661  0.00336685]
14000 [ 0.00658195 -0.00065817  0.00328006  0.00328029]
15000 [ 0.00560478 -0.00056047  0.00279313  0.00279327]
16000 [ 0.00545705 -0.00054573  0.00271951  0.00271964]
17000 [ 0.00531497 -0.00053151  0.00264871  0.00264883]
18000 [ 0.00442368 -0.00044236  0.00220455  0.00220462]
19000 [ 0.0040118  -0.00040118  0.0019993   0.00199934]


array([ 0.00112962, -0.00011296,  0.00056296,  0.00056296])

In [126]:
mini3_4, minis3_4 = gradient_descent_alpha(f,np.array([0.1, -0.1, 0.1, 0.1]), 
                                           tol=1e-8, num_epochs=int(1e+6))
mini3_4

2000 [ 0.02897001 -0.00289649  0.01442765  0.01444659]
3000 [ 0.0224126  -0.00224116  0.01116499  0.01117377]
4000 [ 0.01862085 -0.00186183  0.00927727  0.0092823 ]
5000 [ 0.01261088 -0.00126098  0.00628402  0.00628543]
6000 [ 0.01136826 -0.00113679  0.00566487  0.00566606]
7000 [ 0.00984261 -0.00098422  0.00490474  0.00490556]
8000 [ 0.00850093 -0.00085004  0.00423625  0.00423677]
9000 [ 0.0078134  -0.00078127  0.00389369  0.00389406]
10000 [ 0.00683863 -0.00068383  0.00340797  0.00340822]
11000 [ 0.00626798 -0.00062679  0.00312361  0.0031238 ]
12000 [ 0.00592926 -0.00059281  0.00295482  0.00295498]
13000 [ 0.00559663 -0.00055967  0.00278907  0.0027892 ]
14000 [ 0.00517074 -0.00051707  0.00257684  0.00257694]
15000 [ 0.00466931 -0.00046693  0.00232696  0.00232704]
16000 [ 0.00461601 -0.00046158  0.00230039  0.00230047]
17000 [ 0.00428851 -0.00042885  0.00213719  0.00213725]
18000 [ 0.00377754 -0.00037775  0.00188255  0.0018826 ]
19000 [ 0.00360502 -0.0003605   0.00179658  0.00179662]


array([ 0.00113761, -0.00011376,  0.00056694,  0.00056694])