### $X=\left [ \begin{matrix} 1 & 2 & 3\\  4 & 5 & 6 \\ 7 & 8 & 9\end{matrix}\right]$

In [1]:
import numpy as np
import scipy.stats

In [2]:
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# X = np.array([[1, 2], [7, 4], [5, 6]])
#X_normlized = scipy.stats.zscore(X)
#X_normlized

In [3]:
eigvals, eigvsh = np.linalg.eig(X @ X.T)
#eigvals, eigvsh = np.linalg.eig(X_normlized.dot(X_normlized.T))
prin_com = eigvsh[np.argmax(eigvals)]
prin_com

array([-0.21483724, -0.88723069,  0.40824829])

In [4]:
scipy.stats.zscore(prin_com)

array([ 0.03106961, -1.23998407,  1.20891446])

### 统计

In [5]:
M = np.mean(X.T, axis=1)
C = X - M
V = np.cov(C.T)
V

array([[9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.]])

In [6]:
values, vectors = np.linalg.eig(V)

In [7]:
P = vectors.T @ C.T
P.T

array([[ 2.22044605e-16, -5.19615242e+00,  4.44089210e-16],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-2.22044605e-16,  5.19615242e+00, -4.44089210e-16]])

### 使用`Sklearn`

In [8]:
from sklearn.decomposition import PCA

In [9]:
pca = PCA(2)
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [10]:
pca.components_

array([[-0.57735027, -0.57735027, -0.57735027],
       [ 0.        , -0.70710678,  0.70710678]])

In [11]:
pca.explained_variance_

array([27.,  0.])

In [12]:
pca.transform(X)

array([[ 5.19615242e+00,  4.44089210e-16],
       [ 0.00000000e+00,  0.00000000e+00],
       [-5.19615242e+00, -4.44089210e-16]])

In [13]:
P.T

array([[ 2.22044605e-16, -5.19615242e+00,  4.44089210e-16],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-2.22044605e-16,  5.19615242e+00, -4.44089210e-16]])