In [2]:
import numpy as np
import scipy.linalg as scila

### 三角矩阵
三角矩阵的特征值是其对角线元素 

In [21]:
lower_tri = np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)
lower_tri

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [23]:
evals, evecs = scila.eig(lower_tri)

In [24]:
evals

array([9.+0.j, 5.+0.j, 1.+0.j])

In [25]:
evecs

array([[ 0.        ,  0.        ,  0.70436073],
       [ 0.        ,  0.4472136 , -0.70436073],
       [ 1.        , -0.89442719,  0.08804509]])

### Pascal矩阵

In [15]:
tri1 = scila.pascal(5, kind='upper')
upper_tri

array([[1, 1, 1, 1, 1],
       [0, 1, 2, 3, 4],
       [0, 0, 1, 3, 6],
       [0, 0, 0, 1, 4],
       [0, 0, 0, 0, 1]], dtype=uint64)

In [26]:
evals, evecs = scila.eig(upper_tri)
evals

array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j])